apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment-jenkins
  labels:
    app: pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe
  template:
    metadata:
      labels:
        app: pfe
    spec:
      containers:
      - name: spring-artifact
        image: maroua20/spring-image-jenkins:${BUILD_NUMBER}
        args:
         - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600       
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password    
